name: super_island
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.4.0
  flame_audio: ^1.3.2
  flutter_riverpod: ^2.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/battle/bg/
    - assets/images/bar/
    - assets/images/icons/

    - assets/audio/

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-Medium.otf

    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf

    - family: SVN
      fonts:
        - asset: assets/fonts/SVN-Titillium-bold.ttf
